### ISSUE TITLE
layers do not have data

### ISSUE THREAD

**Issue by raymondnijssen** [Mativane/wow_gis#1]
Funny idea for a plugin! :) So I tried it and figured out that the layers do not contain any data (vector) or show a map (raster). Tried epsg codes 28992, 4326, 3857 and 32662.

i also think pointing to a server by ip address (and port number) is not too handy:

http://18.224.109.62:8080/geoserver/wfs?

**Comment by Mativane** [comment]
Sadly, I cannot reproduce your error. I tried this plugin on diffrent computers (both windows and linux) with diffrent QGIS 3 versions and imported layers always contained data as they should. 

Are you able to give me some more info about your error? What QGIS version are you running? Did you have stable internet connection? If you try it again, does the same bug appears every time?

Also, 32662 is correct EPSG for this data, but you shouldn't have to set it yourself, it should be downloaded in right crs by itself.

**Comment by raymondnijssen** [comment]
Here's my error in qgis:

2020-02-20T22:36:10     WARNING    Returned image is flawed [Content-Type: image/geotiff; URL: http://18.224.109.62:8080/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=-30140.83031344746632,-8333.817678424718906,35139.15613463405316,15764.45499288339852&CRS=EPSG:32662&WIDTH=580&HEIGHT=214&LAYERS=wowgis:r_azeroth&STYLES=&FORMAT=image/geotiff&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE]

**Comment by jmonticolo** [comment]
To reproduce the conditions of the issue, as for a QGIS issue, I advise you to go in the QGIS menu help/about, click in the dialog, Ctrl+A and then Ctrl+C. Finally paste here for get QGIS, OS version and other details.
