### ISSUE TITLE
UI doesn't work properly

### ISSUE THREAD

**Issue by ismailsunni** [Mativane/wow_gis#2]
When I tried to open the plugin, I got this dialog
![image](https://user-images.githubusercontent.com/1421861/74921830-97995c00-53ce-11ea-8065-e355cb8d03dd.png)

as you can see, the widgets are crumbled. I think it's because of my high-resolution screen (or maybe not).

Tested on Ubuntu 18.04, QGIS 3.10, XPS 13, resolution 3200x1800

Nice plugin!

**Comment by jmonticolo** [comment]
This is because `WoWGISDialogBase` and GroupBoxes for `wow_gis_dialog_base_raster.ui` and `wow_gis_dialog_base_vector.ui` have no Layout defined (QVBoxLayout IMHO).

**Comment by Mativane** [comment]
Yes, thank you for reporting it @ismailsunni and thank you for advice @jmonticolo . This will be fixed in next update.
