### ISSUE TITLE
Layer invalid/ lost geoserver connection error

### ISSUE THREAD

**Issue by Steph-Gage** [Mativane/wow_gis#3]
Hi, 
I was excited to give this a try and briefly opened raster/vector files at the beginning of February perfectly fine, however upon trying today I recieved this error and couldn't work my own way around it in QGIS; "Layer is invaild or connection with geoserver is lost! Please report this issue." 
Layers don't appear to be able to load in at all.

Please feel free to ignore if busy with real life things!

**Comment by Mativane** [comment]
Indeed the connection to server was remaining lost during last month. The issue is known and I will try to repair it whenever I will have a bit of free time. 
Thank you for your kind comment
